// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhamMemThueXe.Data;

#nullable disable

namespace PhamMemThueXe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251031044407_AddImageURLToXe")]
    partial class AddImageURLToXe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhamMemThueXe.Models.BangGia", b =>
                {
                    b.Property<int>("MaBangGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBangGia"));

                    b.Property<decimal>("DonGiaTheoNgay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaLoaiXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.HasKey("MaBangGia");

                    b.HasIndex("MaLoaiXe");

                    b.ToTable("BangGias");

                    b.HasData(
                        new
                        {
                            MaBangGia = 1,
                            DonGiaTheoNgay = 500000m,
                            MaLoaiXe = 1,
                            NgayApDung = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            MaBangGia = 2,
                            DonGiaTheoNgay = 800000m,
                            MaLoaiXe = 2,
                            NgayApDung = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            MaBangGia = 3,
                            DonGiaTheoNgay = 1200000m,
                            MaLoaiXe = 3,
                            NgayApDung = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("PhamMemThueXe.Models.ChiTietHopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<string>("BienSoXe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DonGiaTaiThoiDiemThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHopDong", "MaXe");

                    b.HasIndex("MaXe");

                    b.ToTable("ChiTietHopDongs");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("HoTenNVLap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<string>("DiaDiemNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaDiemTra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTenKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNVLap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDatXe")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhanXe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraXe")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoaiKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienDatCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaDatXe");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChiCoQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoCMND")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SoHoKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKH");

                    b.HasIndex("SoCMND")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.LoaiXe", b =>
                {
                    b.Property<int>("MaLoaiXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiXe"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiXe");

                    b.ToTable("LoaiXes");

                    b.HasData(
                        new
                        {
                            MaLoaiXe = 1,
                            MoTa = "Xe sedan, hatchback 4 chỗ ngồi",
                            TenLoaiXe = "Xe 4 chỗ"
                        },
                        new
                        {
                            MaLoaiXe = 2,
                            MoTa = "Xe SUV, crossover 7 chỗ ngồi",
                            TenLoaiXe = "Xe 7 chỗ"
                        },
                        new
                        {
                            MaLoaiXe = 3,
                            MoTa = "Xe minibus 16 chỗ ngồi",
                            TenLoaiXe = "Xe 16 chỗ"
                        });
                });

            modelBuilder.Entity("PhamMemThueXe.Models.PhieuDatXe", b =>
                {
                    b.Property<int>("MaDatXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatXe"));

                    b.Property<string>("HoTenKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiXe")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDuKienNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiXeDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDatXe");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaLoaiXe");

                    b.ToTable("PhieuDatXes");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            MaNhanVien = 1,
                            HoTen = "Quản trị viên hệ thống",
                            MatKhauHash = "$2a$11$IDk4pG8Tsk2zJvfc5wDUHOsdYNSsK4N7zCgRoLnGs2H4GfOW2FEu2",
                            Quyen = "Admin",
                            TenDangNhap = "admin"
                        });
                });

            modelBuilder.Entity("PhamMemThueXe.Models.Xe", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaLoaiXe")
                        .HasColumnType("int");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaXe");

                    b.HasIndex("BienSoXe")
                        .IsUnique();

                    b.HasIndex("MaLoaiXe");

                    b.ToTable("Xes");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.BangGia", b =>
                {
                    b.HasOne("PhamMemThueXe.Models.LoaiXe", "LoaiXe")
                        .WithMany()
                        .HasForeignKey("MaLoaiXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.ChiTietHopDong", b =>
                {
                    b.HasOne("PhamMemThueXe.Models.HopDong", "HopDong")
                        .WithMany("ChiTietHopDongs")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhamMemThueXe.Models.Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.HoaDon", b =>
                {
                    b.HasOne("PhamMemThueXe.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaHopDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhamMemThueXe.Models.TaiKhoan", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.HopDong", b =>
                {
                    b.HasOne("PhamMemThueXe.Models.PhieuDatXe", "PhieuDatXe")
                        .WithMany()
                        .HasForeignKey("MaDatXe")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PhamMemThueXe.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhamMemThueXe.Models.TaiKhoan", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuDatXe");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.PhieuDatXe", b =>
                {
                    b.HasOne("PhamMemThueXe.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhamMemThueXe.Models.LoaiXe", "LoaiXe")
                        .WithMany()
                        .HasForeignKey("MaLoaiXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.Xe", b =>
                {
                    b.HasOne("PhamMemThueXe.Models.LoaiXe", "LoaiXe")
                        .WithMany()
                        .HasForeignKey("MaLoaiXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("PhamMemThueXe.Models.HopDong", b =>
                {
                    b.Navigation("ChiTietHopDongs");

                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
